/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xianglin_fellowvillager_app_utils_NativeEncrypt */

#ifndef _Included_com_xianglin_fellowvillager_app_utils_NativeEncrypt
#define _Included_com_xianglin_fellowvillager_app_utils_NativeEncrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xianglin_fellowvillager_app_utils_NativeEncrypt
 * Method:    initEncryptLib
 * Signature: (Ljava/lang/lang;)Ljava/lang/lang;
 */
JNIEXPORT void JNICALL Java_com_xianglin_fellowvillager_app_utils_NativeEncrypt_initEncryptLib(
		JNIEnv *, jobject, jobject);
/*
 * Class:     com_xianglin_fellowvillager_app_utils_NativeEncrypt
 * Method:    getPublicKEY
 * Signature: (Ljava/lang;)Ljava/lang;
 */
//JNIEXPORT jstring JNICALL Java_com_xianglin_fellowvillager_app_utils_NativeEncrypt_getPublicKEY(
//		JNIEnv *, jobject);

/*
 * Class:     com_xianglin_fellowvillager_app_utils_NativeEncrypt
 * Method:    getAesKEY
 * Signature: (Ljava/lang;)Ljava/lang;
 */
JNIEXPORT jstring JNICALL Java_com_xianglin_fellowvillager_app_utils_NativeEncrypt_getAesKEY(
		JNIEnv *, jobject);
/*
 * Class:     com_xianglin_fellowvillager_app_utils_NativeEncrypt
 * Method:    gestureEncryptEnter
 * Signature: (Ljava/lang/String/String;Ljava/lang/String/String;)Z
 */
JNIEXPORT jstring JNICALL Java_com_xianglin_fellowvillager_app_utils_NativeEncrypt_gestureEncryptEnter(
		JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_xianglin_fellowvillager_app_utils_NativeEncrypt
 * Method:    gestureEncryptCheck
 * Signature: (Ljava/lang/String/String;Ljava/lang/String/String;)Z
 */
JNIEXPORT jstring JNICALL Java_com_xianglin_fellowvillager_app_utils_NativeEncrypt_gestureEncryptCheck(
		JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_xianglin_fellowvillager_app_utils_NativeEncrypt
 * Method:    gestureEncryptUserExist
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jstring JNICALL Java_com_xianglin_fellowvillager_app_utils_NativeEncrypt_gestureEncryptUserExist(
		JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_xianglin_fellowvillager_app_utils_NativeEncrypt
 * Method:    gestureEncryptUserDelete
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jstring JNICALL Java_com_xianglin_fellowvillager_app_utils_NativeEncrypt_gestureEncryptUserDelete(
		JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_xianglin_fellowvillager_app_utils_NativeEncrypt
 * Method:    getUrlByKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jstring JNICALL Java_com_xianglin_fellowvillager_app_utils_NativeEncrypt_getUrlByKey(
		JNIEnv *, jobject, jstring);

/*
 * Class:     com_xianglin_fellowvillager_app_utils_NativeEncrypt
 * Method:    getRsaByKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jstring JNICALL Java_com_xianglin_fellowvillager_app_utils_NativeEncrypt_getRsaByKey(
		JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
